require 'materialized_views/version'
require 'active_record'
require 'materialized_views/gold_standard_test'
require 'materialized_views/migration_helpers'
require 'materialized_views/materialized_view'
require 'materialized_views/one_to_one'
require 'materialized_views/trigger_definitions'
